[package]
name = "netvars"
version = "0.1.0"
authors = ["Balen <barena.ekusuimii@gmail.com>"]
edition = "2018"

[dependencies]
netvars_derive = { git = "https://github.com/cestef/netvars_derive.git" }
